### ISSUE TITLE
Dynare

### ISSUE THREAD

**Issue by ispanos** [ptinopedila/ptinopedila#34]
Figure out how to install Dynare on Matlab and Octave.

**Comment by ispanos** [comment]
Matlab dep. notes:

```yaml
type: rpm-ostree
install:
  - fontconfig
  - freetype
  - gcc # Needed compiler
  - gcc-g++ # Needed compiler # Not installed
  - gfortran # Needed compiler # Not installed
  - libnsl # legacy version of libnsl library # Not installed
  - libva-utils
  # - libva-vdpau-driver
  - libX11-devel # Not installed
  - libxcrypt-compat # provides libcrypt.so.1
  - libXext-devel # Not installed
  - libXi-devel # Not installed
  - libXmu-devel # Not installed
  - libXtst-devel # Not installed
  - vdpauinfo # Not installed
```
